accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('changepassword', views.changepassword, name='changepassword'),
    path('userdatachangeview', views.UserDataChangeView, name='userdatachange'),
    path('password_reset', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('', views.loginCas, name='loginCas'),
]

elearning/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('elearning/', include('elearningweb.urls')),
    path('', RedirectView.as_view(url='/elearning/')),
    path('account/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()

elearningweb/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('courses/<int:page>', views.CoursesView, name='courses'),
    path('class/completetest/<int:testID>', views.completeTest, name='completetest'),
    path('class/completetest/<int:testID>/finished', views.finishView, name='finished'),
    path('class/<int:classID>/createtest', views.createTest, name='createtest'),
    path('managetest/<int:testID>/', views.manageTest,name='managetest'),
    path('managetest/<int:testID>/addquestions', views.addQuestions, name='addquestions'),
    path('managetest/<int:testID>/editquestion/<int:questionID>', views.editQuestion, name='editquestion'),
    path('class/<int:pk>', views.ClassesView, name='class'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('course/<int:pk>', views.CourseDetailView.as_view(), name='course_detail'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('course/add/', views.AddCourse, name='addcourse'),
    path('course/join/<int:kurs>',views.JoinCourse,name='join_course'),
    path('course/quit/<int:kurs>',views.QuitCourse,name='quit_course'),
    path('course/edit/<int:kurs>',views.EditCourse,name='edit_course'),
    path('user_courses', views.UserCourses, name ='user_courses'),
    path('courses/testscores/<int:testID>',views.testScores,name='testscores'),
    path('class/add/', views.AddClass, name='addclass'),
    path('class/delete/<int:classId>',views.DeleteClass,name='delete_class'),
    path('user_courses/<int:page>', views.UserCourses, name ='user_courses'),
    path('course/addinstr/<int:kurs>', views.AddCourseInstructor, name ='add_instr'),
    path('userdetailview', views.UserDetailView, name='userdetailview'),
    path('class/edit/<int:classId>',views.EditClass,name='edit_class'),
]

dbhandler/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from ckeditor.fields import RichTextField

# Modele

class Module(models.Model):
    name = models.CharField(max_length=64)
    def __str__(self):
        return self.name

class CourseType(models.Model):
    name = models.CharField(max_length=64)
    def __str__(self):
        return self.name

class InstructorData(models.Model):
    home_page = models.CharField(max_length = 40)

class CustomUser(AbstractUser):
    pass
    instructor_data = models.ForeignKey('InstructorData', on_delete=models.CASCADE, null=True, blank=True)

class Course(models.Model):
    name = models.CharField(max_length = 64)
    course_type = models.ForeignKey('CourseType', on_delete=models.CASCADE)
    module_id = models.ForeignKey('Module', on_delete=models.CASCADE)
    description = models.TextField()
    password = models.CharField(max_length = 16)
    def __str__(self):
        return self.name
        
class Instructor(models.Model):
    user_id = models.ForeignKey('CustomUser', on_delete=models.CASCADE)
    course_id = models.ForeignKey('Course', on_delete=models.CASCADE)

class Participant(models.Model):
    user_id = models.ForeignKey('CustomUser', on_delete=models.CASCADE)
    course_id = models.ForeignKey('Course', on_delete=models.CASCADE)

class Class(models.Model):
    name = models.CharField(max_length = 64)
    description = models.TextField()
    course_id = models.ForeignKey('Course', on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Content(models.Model):
    valid_until = models.DateTimeField(null=True, blank=True)
    text = RichTextField()
    class_id = models.ForeignKey('Class', on_delete=models.CASCADE)

class Comment(models.Model):
    text = models.TextField()
    author_id = models.ForeignKey('CustomUser', on_delete=models.CASCADE)
    class_id = models.ForeignKey('Class', on_delete=models.CASCADE)

class Test(models.Model):
    name = models.CharField(max_length = 64)
    description = models.TextField()
    class_id = models.ForeignKey('Class', on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Question(models.Model):
    question_text = RichTextField()
    test_id = models.ForeignKey('Test', on_delete=models.CASCADE)

class Answer(models.Model):
    answer_text = models.TextField()
    is_good = models.SmallIntegerField()
    question_id = models.ForeignKey('Question', on_delete=models.CASCADE)

class TestResult(models.Model):
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE)
    test = models.ForeignKey('Test', on_delete=models.CASCADE)
    result = models.IntegerField()
    maxScore = models.IntegerField()

elearningweb/models.py
from django.db import models

# Create your models here.

elearningweb/views.py
from django.shortcuts import render, redirect

from urllib.parse import urlencode
from django.urls import reverse
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User
from django.template import Context, Template
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import datetime

from django.views.generic import ListView, TemplateView, DetailView, FormView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from dbhandler.models import *
from .forms import *

# Create your views here.


def CoursesView(request,**kwargs):
    if not request.user.is_authenticated:
        return render(request, 'login_error.html')
    fname=''
    lname=''
    cname=''
    mname=''
    instructors = Instructor.objects.all().order_by('pk')
    if 'course_name' in request.GET:
        if request.GET['course_name'] is not '':
            cname=request.GET['course_name']
            instructors=instructors.filter(course_id__name__contains=cname)
    if 'instr_name' in request.GET:
        if request.GET['instr_name'] is not '':
            fname=request.GET['instr_name']
            instructors=instructors.filter(user_id__first_name__contains=fname)
    if 'instr_lastname' in request.GET:
        if request.GET['instr_lastname'] is not '':
            lname=request.GET['instr_lastname']
            instructors=instructors.filter(user_id__last_name__contains=lname)
    if 'module_name' in request.GET:
        if request.GET['module_name'] is not '':
            mname=request.GET['module_name']
            instructors=instructors.filter(course_id__module_id__name__contains=mname)
    search_query = '?course_name='+cname+'&instr_name='+fname+'&instr_lastname'+lname+'&module_name='+mname

    page = kwargs['page']

    paginator = Paginator(instructors, 10)
    try:
        instructors = paginator.page(page)
    except PageNotAnInteger:
        instructors = paginator.page(1)
    except EmptyPage:
        instructors = paginator.page(paginator.num_pages)
    c = {
        'search_query':search_query,
        'instructors':instructors,
    }

    return render(request,"courses.html",c)

#TO-DO: NAPRAWIC WYSZUKIWANIE
# class CoursesView(ListView):
#     model = Course
#     template_name = 'courses.html'
#     def get_queryset(self):
#         result = super(CoursesView, self).get_queryset()
#         query = self.request.GET.get('search')
#         if query:
#              result = result.filter(
#                     name__icontains=query
#             )
        


class CourseDetailView(DetailView):
    model = Course
    template_name='course_detail.html'

def ClassesView(request,**kwargs):
    if not request.user.is_authenticated:
        return render(request, 'login_error.html')

    k = Class.objects.get(pk=kwargs['pk'])
    if not (Participant.objects.filter(course_id=k.course_id,user_id=request.user).exists() or Instructor.objects.filter(course_id=k.course_id,user_id=request.user).exists()):
        if not request.user.has_perm('dbhandler.view_class'):
            return render(request, 'permission_error.html')   

    if request.method == 'POST':
        comment = request.POST['comment']
        author = int(request.POST['author']) 
        cid = int(request.POST['id'])
        c=Comment(text=comment, author_id=request.user, class_id=Class.objects.get(id=cid))
        c.save()
        return redirect('class', kwargs['pk']) 

    cont = Content.objects.get(class_id=k, valid_until__isnull=True)

    c = {
        'class': k,
        'content':cont
    }
    
    return render(request, 'class.html', c)          


# class ClassesView(DetailView):
#     model = Class
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         k = Class.objects.get(pk=self.kwargs['pk'])
#         context['content'] = Content.objects.get(class_id=k, valid_until__isnull=True)
#         return context
#     def post(self, request, *args, **kwargs):
#         comment = request.POST['comment']
#         author = int(request.POST['author']) 
#         cid = int(request.POST['id'])
#         c=Comment(text=comment, author_id=request.user, class_id=Class.objects.get(id=cid))
#         c.save()
#         return redirect('class', kwargs['pk'])            
#     template_name = 'class.html'


class HomeView(TemplateView):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('user_courses', 1)
        else:
            return render(request, 'index.html')

def completeTest(request,**kwargs):
    if not request.user.is_authenticated:
        return render(request, 'login_error.html')
    test=Test.objects.get(id=kwargs['testID'])
    classobj=Class.objects.get(id=test.class_id_id)
    if not (Participant.objects.filter(course_id=classobj.course_id,user_id=request.user).exists() or Instructor.objects.filter(course_id=classobj.course_id,user_id=request.user).exists()):
        if not request.user.is_staff:
            return render(request, 'permission_error.html')
    try:
        Test.objects.get(id=kwargs['testID'])
    except Test.DoesNotExist:
        return render(request, 'test_error.html')
    questionList = Question.objects.filter(test_id=kwargs['testID'])
    answerList = []
    for q in questionList:
        answerList.extend(Answer.objects.filter(question_id_id=q.id))
    c={
        'test':test,
        'questions':questionList,
        'answers':answerList,
        'qCount':questionList.count()
        }
    return render(request,"completeTest.html",c)

def finishView(request,**kwargs):
    if not request.user.is_authenticated:
        return render(request, 'login_error.html')
    test=Test.objects.get(id=kwargs['testID'])
    classobj=Class.objects.get(id=test.class_id_id)
    if not (Participant.objects.filter(course_id=classobj.course_id,user_id=request.user).exists() or Instructor.objects.filter(course_id=classobj.course_id,user_id=request.user).exists()):
        if not request.user.is_staff:
            return render(request, 'permission_error.html')
    try:
        Test.objects.get(id=kwargs['testID'])
    except Test.DoesNotExist:
        return render(request, 'test_error.html')
    if request.method == 'POST':
        qCount=int(request.POST['qc'])
        ansList=[]
        questionsList=Question.objects.filter(test_id=kwargs['testID'])
        allAnsList=[]
        for q in questionsList:
            allAnsList.extend(Answer.objects.filter(question_id_id=q.id))
        for i in range(1,qCount+1):
            ch=int(request.POST['Question%d' % i])
            ansList.append(ch)
        score = 0
        for a in allAnsList:
            if a.id in ansList:
                if a.is_good == 1:
                    score = score + 1
        c={
            'checked':ansList,
            'test':test,
            'questions':questionsList,
            'answers':allAnsList,
            'score':score,
            'qCount':qCount
        }
        try:
            result = TestResult.objects.get(user=request.user.id,test=test.id)
            if result.result < score:
                result.result = score
            if result.maxScore < qCount:
                result.maxScore = qCount
            result.save()
        except TestResult.DoesNotExist:
            result = TestResult(user=request.user,test=test,result=score,maxScore=qCount)
            result.save()
    return render(request,"finishedTest.html",c)

def testScores(request,**kwargs):
    if not request.user.is_authenticated:
        return render(request, 'login_error.html')
    test=Test.objects.get(id=kwargs['testID'])
    classobj=Class.objects.get(id=test.class_id_id)    
    try:
        Instructor.objects.get(user_id_id=request.user.id,course_id_id=classobj.course_id_id)
    except Instructor.DoesNotExist:
        if not request.user.is_staff:
            return render(request, 'permission_error.html')
    try:
        Test.objects.get(id=kwargs['testID'])
    except Test.DoesNotExist:
        return render(request, 'test_error.html')
    c={
        'test':test,
        'users':CustomUser.objects.all(),
        'results':TestResult.objects.filter(test=test)
        }
    return render(request,"testScores.html",c)

def createTest(request,**kwargs):
    if not request.user.is_authenticated:
        return render(request, 'login_error.html')
    classobj=Class.objects.get(id=kwargs['classID'])    
    try:
        Instructor.objects.get(user_id_id=request.user.id,course_id_id=classobj.course_id_id)
    except Instructor.DoesNotExist:
        if not request.user.is_staff:
            return render(request, 'permission_error.html')
    f = CreateTestForm()

    c = {
        'form': f
    }
    if request.method == 'POST':
        testName = request.POST['name']
        testDesc = request.POST['description']
        ClassId = int(kwargs['classID'])
        t=Test(name=testName,description=testDesc,class_id_id=ClassId)
        t.save()
        return redirect('../../managetest/%d/addquestions' % t.id)
    return render(request,"createTest.html",c)


def addQuestions(request,**kwargs):
    if not request.user.is_authenticated:
        return render(request, 'login_error.html')
    test=Test.objects.get(id=kwargs['testID'])
    classobj=Class.objects.get(id=test.class_id_id)    
    try:
        Instructor.objects.get(user_id_id=request.user.id,course_id_id=classobj.course_id_id)
    except Instructor.DoesNotExist:
        if not request.user.is_staff:
            return render(request, 'permission_error.html')
    if request.method == 'POST':
            qText = request.POST['question_text']
            ans = [
                request.POST['answer_1'],
                request.POST['answer_2'],
                request.POST['answer_3'],
                request.POST['answer_4']
            ]
            corAns = request.POST['correct']

elearningweb/templates/addCourseInstructor.html
{% extends "base.html" %}

{% block banner %}
    <h1 class = "banner" >Dodaj prowadzącego do kursu</h1>
{% endblock %}

{% block content %}
<form method="post" class="small-form">
    {% csrf_token %}
    {% for field in form %}
        <div class="input-field fieldWrapper">
        {{ field.label_tag }} {{ field }}
        </div>
    {% endfor %}
    <button class="btn-large z-depth-0" type="submit" name="action">Dodaj</button>
</form>
{% endblock %}

elearningweb/templates/addQuestions.html
{% extends "base.html" %}

{% block banner %}
Dodawanie pytania
{% endblock %}

{% block content %}
    <form method="POST" class="form">
        {% csrf_token %}
        {{ form.media }}
        <br><br>
        {{ form.non_field_errors }}
        <div class="fieldWrapper">
            {{ form.question_text }}
        </div>

        <div class="fieldWrapper">
            {{ form.answer_1.label_tag }}
            {{ form.answer_1 }}
        </div>

        <div class="fieldWrapper">
            {{ form.answer_2.label_tag }}
            {{ form.answer_2 }}
        </div>

        <div class="fieldWrapper">
            {{ form.answer_3.label_tag }}
            {{ form.answer_3 }}
        </div>

        <div class="fieldWrapper">
            {{ form.answer_4.label_tag }}
            {{ form.answer_4 }}
        </div>

        <span>{{form.correct.label}}:</span>
        {% for radio in form.correct %}
        <div>
            <label>
                {{ radio.tag }}
                <span class="radio">{{ radio.choice_label }}</span>
            </label>
        </div>
        {% endfor %}
        <button class="btn-large z-depth-0" type="submit" name="action">Dodaj pytanie</button>
        <a href="{% url 'managetest' testID %}" class="btn-large z-depth-0">Wróć do testu</a>
    </form>
{% endblock %}

elearningweb/templates/addcourse.html
{% extends "base.html" %}

{% block banner %}
Dodawanie Kursów
{% endblock %}

{% block content %}
<form method="post" class="small-form">
    {% csrf_token %}
    {% for field in form %}
        <div class="input-field fieldWrapper">
        {{ field.label_tag }} {{ field }}
        </div>
    {% endfor %}
    <button class="btn-large z-depth-0" type="submit" name="action">Dodaj</button>
</form>
{% endblock %}

elearningweb/templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="pl">
<head>
  {% block title %}<title>Platforma E-Learningowa</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
  <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' async></script>
</head>
<body>
  <nav class="z-depth-0 white">
    <a href="{% url 'index' %}" class="left brand-logo"><img src="{% static 'logo.jpg' %}" class="responsive-img"></a>
    <ul id="nav" class="right">

      {% if user.is_authenticated %}
        <li><a href="{% url 'courses' 1 %}" class="black-text">Wszystkie kursy</a></li>
        <li><a href="{% url 'user_courses' 1 %}" class="black-text">Twoje kursy</a></li>
        {% if user.is_staff %}
        <li><a href="/admin" class="black-text">Panel administratora</a></li>
        {% endif %}
        <li><a href="{% url 'userdetailview' %}" class="black-text">{{ user.get_username}}</a></li>
        <!-- wylogowanie -->
        <li>
          <a href="javascript:{document.getElementById('logout').submit()}" class="btn z-depth-0">Wyloguj się</a>
          <form action="{% url 'logout' %}" method="POST" id="logout">{% csrf_token %}<input type="hidden"></form>
        </li>
      {% else %}
        <li><a href="{% url 'login' %}" class="btn z-depth-0">Zaloguj się</a></li>
      {% endif %}
    </ul>
  </nav>
  <main class="container center-align">
    <h4>{% block banner %}{% endblock %}</h4>
    {% block content %}
    {% endblock %}

    {% if messages %}
      {% for message in messages %}
        {% if message.tags == 'success' %}
          <body onload="M.toast({html: '{{message}}', classes: 'success', displayLength: 2000})">
        {% else %}
          <p class="error">{{message}}</p>
        {% endif %}
      {% endfor %}
    {% endif %}
  </main>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

elearningweb/templates/changeCourseData.html
{% extends "base.html" %}

{% block banner %}
Edytowanie Kursu
{% endblock %}

{% block content %}
<form method="post" class="small-form">
    {% csrf_token %}
    {% for field in form %}
        <div class="input-field fieldWrapper">
        {{ field.label_tag }} {{ field }}
        </div>
    {% endfor %}
    <button class="btn-large z-depth-0" type="submit" name="action">Zmień</button>
</form>
{% endblock %}

elearningweb/templates/changePassword.html
{% extends "base.html" %}

{% block banner %}
Zmiana Hasła
{% endblock %}

{% block content %}
	<div class="small-form">
        <form method="POST">
        	{% csrf_token %}
        	<div class="input-field">
            	<input type="password" name="oldpassword" required>
            	<label for="oldpassword">Wprowadź stare hasło</label>
            </div>
            <div class="input-field">
            	<input type="password" name="newpassword" required>
            	<label for="newpassword">Wprowadź nowe hasło</label>
            </div>
            <div class="input-field">
            	<input type="password" name="newpassword2" required>
            	<label for="newpassword2">Potwierdź nowe hasło</label>
            </div>
            <button class="btn z-depth-0" type="submit">Zmień hasło</button>
        </form>
    </div>
{% endblock %}

elearningweb/templates/class.html
{% extends "base.html" %}
{% load auth_extras %}

{% block banner %}
{{class.name}}
{% endblock %}

{% block content %}
<div class= "left-align">
    <a href="{% url 'course_detail' class.course_id_id %}" id="link-courses-details"> << Powrót do kursu</a>
    <div>
        {% if perms.dbhandler.change_class %}
            <a class="btn" style="float: right;" href="{% url 'edit_class' class.id %}">Edytuj zajęcia</a>
        {% endif %}
        <div class="break"></div>
        <p> {{class.description}}</p>
    </div>
    <div class= "content">
            <p>{{content.text|safe|escape}}</p>
    </div>
    <div class="break"></div>
    <div class= "tests">
        <h5>Testy do zajęć</h5>
        <ul  class="collection left-align">
            {% for test in class.test_set.all %}
                <li class="collection-item" style="line-height: 38px;">
                    <a href="{% url 'completetest' test.id %}">{{test.name}}</a>
                    {% if user|has_group:'Prowadzący' %}
                    <a href="{% url 'testscores' test.id %}" class="btn" style="float: right;">Zobacz wyniki</a>
                    <a href="{% url 'managetest' test.id %}" class="btn" style="float: right;">Edytuj Test</a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
    {% if perms.dbhandler.add_test %}
		<a href="{% url 'createtest' class.id %}" class="btn">Dodaj test</a>
	{% endif %}
    <div class="break"></div>
    <div class= "comments">
        <h5>Komentarze </h5> 
        <div class="break"></div>
         {% for comment in class.comment_set.all %}
            <thread style="color:grey"> {{comment.author_id}} </thread>
            <div class="nav-wrapper blue lighten-5">
                 {{comment.text}}
            </div>
            <div class="break"></div>
         {% endfor %}  
        <div class="break"></div>
        <h6 class>Dodaj komentarz</h6>
        <form method= "POST">
            {% csrf_token %}
            <input name="comment" type="text" required>
            <input name="author" type="hidden"  value="{{ user.id}}"/>
            <input name="id" type="hidden"  value="{{ class.id }}"/>
            <button class="btn" type="submit">Dodaj komentarz</button>
        </form>
    </div>
</div>
{% endblock %}

elearningweb/templates/class_edit.html
{% extends "base.html" %}

{% block banner %}
Edycja zajęć 
{% endblock %}

{% block content %}
<form method="post" class="">
    {% csrf_token %}
    {{ form.media }}
    {% for field in form %}
        <div class="input-field fieldWrapper">
            {{ field.label_tag }} {{ field }}
        </div>
    {% endfor %}
    <button class="btn z-depth-0" type="submit" name="action">Zapisz</button>
</form>
{% endblock %}

elearningweb/templates/course_detail.html
{% extends "base.html" %}
{% load auth_extras %}

{% block banner %}
{% endblock %}

{% block content %}
	<a href="{% url 'courses' 1 %}" class="left"><< Lista kursów</a>
	<br>
	<div class="left-align">
		<h4>{{ course.name }}</h4>
		<div class="options right">
            <a href="{% url 'add_instr' course.id %}" class="btn z-depth-0">Dodaj prowadzącego</a>
			<a href="{% url 'edit_course' course.id %}" class="btn z-depth-0">Edytuj Kurs</a>
			<a href="{% url 'quit_course' course.id %}" class="btn z-depth-0">Zrezygnuj z kursu</a>
			<a href="{% url 'addclass' %}" class="btn z-depth-0">Dodaj zajęcia</a>
		</div>
		<div class="details">
			Prowadzący: {% for instructor in course.instructor_set.all %}
				{{ instructor.user_id.first_name }}
				{{ instructor.user_id.last_name }}
			{% endfor %}<br>
			{{ course.description }}
		</div>

		<div class="break"></div>

		{% if course.class_set.all %}
			<ul class="collection">
			{% for class in course.class_set.all %}
				<li class="collection-item truncate">
					<a href="{% url 'class' class.id %}">{{ class.name }}</a>
					<span class="grey-text text-lighten-1">&#8195{{ class.description }} </span>
				</li>
			{% endfor %}
			</ul>
		{% else %}
			Brak zajęć.
		{% endif %}

		<div class="break"></div>
		{% if perms.dbhandler.add_class %}
		<a href="{% url 'addclass' %}" class="btn">Dodaj zajęcia</a>
		{% endif %}
	</div>
{% endblock %}

elearningweb/templates/courses.html
{% extends "base.html" %}
{% block banner %}
Dostępne kursy
{% endblock %}
{% block content %}

	<form class="col s12"  method="GET">
		{% csrf_token %}
		<div class="row">
		<div class="input-field col s3">
			<input type="search" name='course_name'>
			<label for="course_name">Nazwa kursu</label>
		</div>
		<div class="input-field col s3">
			<input type="search" name='module_name'>
			<label for="module_name">Nazwa przedmiotu</label>
		</div>
		<div class="input-field col s3">
			<input type="search" name='instr_name'>
			<label for="instr_name">Imię prowadzącego</label>
		</div>
		<div class="input-field col s3">
			<input type="search" name='instr_lastname'>
			<label for="instr_lastname">Nazwisko prowadzącego</label>
		</div>
	</div>
		<button class="btn z-depth-0" type="submit">Wyszukaj</button>
	</form>

<br></br>

	{% if instructors.paginator.count %}
	    <ul class="collection left-align">
			{% for i in instructors %}
				<li class="collection-item">
					{{ i.course_id.name }}
					<span class="grey-text text-lighten-1">{{ i.course_id.module_id.name }} [{{  i.course_id.course_type.name }}] {{ i.user_id.first_name }} {{ i.user_id.last_name }}</span>
					{% if perms.dbhandler.add_participant %}
						<a href="{% url 'join_course' i.course_id.id %}" class="secondary-content">Zapisz się</a>
					{% endif %}
				</li>
			{% endfor %}
		</ul>
	{% else %}
		Brak kursów.
	{% endif %}

	{% if instructors.has_other_pages %}
  <ul class="pagination">
    {% if instructors.has_previous %}
      <li><a class="btn" href="{{ instructors.previous_page_number }}{{search_query}}">&laquo;</a></li>
    {% else %}
      <li><span class="btn" style="color: #444; padding: 0 10px; line-height: 30px; font-size: 1.2rem;">&laquo;</span></li>
    {% endif %}
    {% for i in instructors.paginator.page_range %}
      {% if instructors.number == i %}
        <li ><span class="btn" style="padding: 0 10px; line-height: 30px; font-size: 1.2rem;">{{ i }}</span></li>
      {% else %}
        <li><a class="btn" href="{{ i }}{{search_query}}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if instructors.has_next %}
      <li><a class="btn" href="{{ instructors.next_page_number }}{{search_query}}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span class="btn" style="color: #444; padding: 0 10px; line-height: 30px; font-size: 1.2rem;">&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

	<div class="break"></div>
	{% if perms.dbhandler.add_course %}
		<a href="{% url 'addcourse' %}" class="btn">Dodaj kurs</a>
	{% endif %}
{% endblock %}

elearningweb/templates/permission_error.html
{% extends "base.html" %}

{% block banner %}
BŁĄD
{% endblock %}

{% block content %}
Nie posiadasz uprawnień aby to zrobić!
{% endblock %}